import { Shortcut } from './types/shortcut';

export const defaultShortcuts: Shortcut[] = [
  // General Shortcuts
  {
    id: 'toggle-command-palette',
    actionId: 'toggle-command-palette',
    keys: 'control+k',
    description: 'Open Command Palette',
    category: 'General',
  },
  {
    id: 'search-files',
    actionId: 'search-files',
    keys: 'control+p',
    description: 'Search Files',
    category: 'General',
  },
  {
    id: 'dev-commands',
    actionId: 'dev-commands',
    keys: 'control+shift+p',
    description: 'Developer Commands',
    category: 'General',
  },
  {
    id: 'search-view',
    actionId: 'search-view',
    keys: 'control+f',
    description: 'Search Current View',
    category: 'General',
  },
  {
    id: 'global-search',
    actionId: 'global-search',
    keys: 'control+shift+f',
    description: 'Global Search',
    category: 'General',
  },
  {
    id: 'refresh-jobs',
    actionId: 'refresh-jobs',
    keys: 'control+r',
    description: 'Refresh Jobs',
    category: 'General',
  },
  {
    id: 'upload-zip',
    actionId: 'upload-zip',
    keys: 'control+u',
    description: 'Upload ZIP',
    category: 'General',
  },
  {
    id: 'start-migration',
    actionId: 'start-migration',
    keys: 'control+m',
    description: 'Start Migration',
    category: 'General',
  },
  {
    id: 'download-zip',
    actionId: 'download-zip',
    keys: 'control+d',
    description: 'Download Output ZIP',
    category: 'General',
  },
  {
    id: 'migration-history',
    actionId: 'migration-history',
    keys: 'control+h',
    description: 'Open Migration History',
    category: 'General',
  },
  {
    id: 'open-graph',
    actionId: 'open-graph',
    keys: 'control+g',
    description: 'Open Dependency Graph',
    category: 'General',
  },
  {
    id: 'open-job-details',
    actionId: 'open-job-details',
    keys: 'control+j',
    description: 'Open Job Details',
    category: 'General',
  },
  {
    id: 'toggle-sidebar',
    actionId: 'toggle-sidebar',
    keys: 'control+b',
    description: 'Toggle Sidebar',
    category: 'General',
  },
  {
    id: 'focus-search',
    actionId: 'focus-search',
    keys: 'control+l',
    description: 'Focus Search Box',
    category: 'General',
  },
  {
    id: 'open-settings',
    actionId: 'open-settings',
    keys: 'control+,',
    description: 'Open Settings',
    category: 'Settings',
  },
  {
    id: 'toggle-theme',
    actionId: 'toggle-theme',
    keys: 'control+shift+l',
    description: 'Toggle Theme',
    category: 'Settings',
  },
  {
    id: 'help-dialog',
    actionId: 'help-dialog',
    keys: 'f1',
    description: 'Help & Keyboard Shortcuts',
    category: 'General',
  },
  {
    id: 'cancel-action',
    actionId: 'cancel-action',
    keys: 'escape',
    description: 'Close Dialog / Cancel Current Action',
    category: 'General',
  },

  // Navigation Shortcuts
  {
    id: 'nav-dashboard',
    actionId: 'nav-dashboard',
    keys: 'alt+1',
    description: 'Go to Dashboard',
    category: 'Navigation',
  },
  {
    id: 'nav-upload',
    actionId: 'nav-upload',
    keys: 'alt+2',
    description: 'Go to Upload Section',
    category: 'Navigation',
  },
  {
    id: 'nav-jobs',
    actionId: 'nav-jobs',
    keys: 'alt+3',
    description: 'Go to Recent Jobs',
    category: 'Navigation',
  },
  {
    id: 'nav-job-details',
    actionId: 'nav-job-details',
    keys: 'alt+4',
    description: 'Go to Job Details',
    category: 'Navigation',
  },
  {
    id: 'nav-graph',
    actionId: 'nav-graph',
    keys: 'alt+5',
    description: 'Go to Dependency Graph',
    category: 'Navigation',
  },
  {
    id: 'nav-ai-logs',
    actionId: 'nav-ai-logs',
    keys: 'alt+6',
    description: 'Go to AI Logs',
    category: 'Navigation',
  },
  {
    id: 'nav-reports',
    actionId: 'nav-reports',
    keys: 'alt+7',
    description: 'Go to Reports',
    category: 'Navigation',
  },
  {
    id: 'nav-settings',
    actionId: 'nav-settings',
    keys: 'alt+8',
    description: 'Go to Settings',
    category: 'Navigation',
  },

  // File Explorer Shortcuts (Explorer Context)
  {
    id: 'explorer-move-up',
    actionId: 'explorer-move-up',
    keys: 'arrowup',
    description: 'Move Focus Up',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-move-down',
    actionId: 'explorer-move-down',
    keys: 'arrowdown',
    description: 'Move Focus Down',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-collapse',
    actionId: 'explorer-collapse',
    keys: 'arrowleft',
    description: 'Collapse Folder',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-expand',
    actionId: 'explorer-expand',
    keys: 'arrowright',
    description: 'Expand Folder',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-open',
    actionId: 'explorer-open',
    keys: 'enter',
    description: 'Open File',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-preview',
    actionId: 'explorer-preview',
    keys: 'space',
    description: 'Preview File',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-first',
    actionId: 'explorer-first',
    keys: 'home',
    description: 'Focus First File',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-last',
    actionId: 'explorer-last',
    keys: 'end',
    description: 'Focus Last File',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-page-up',
    actionId: 'explorer-page-up',
    keys: 'pageup',
    description: 'Scroll Explorer Up',
    category: 'Files',
    context: 'explorer',
  },
  {
    id: 'explorer-page-down',
    actionId: 'explorer-page-down',
    keys: 'pagedown',
    description: 'Scroll Explorer Down',
    category: 'Files',
    context: 'explorer',
  },

  // Monaco Editor Shortcuts (Editor Context)
  {
    id: 'editor-find',
    actionId: 'editor-find',
    keys: 'control+f',
    description: 'Find in Code',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-goto-line',
    actionId: 'editor-goto-line',
    keys: 'control+g',
    description: 'Go to Line',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-search-project',
    actionId: 'editor-search-project',
    keys: 'control+shift+f',
    description: 'Search in Project',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-prev-file',
    actionId: 'editor-prev-file',
    keys: 'alt+arrowleft',
    description: 'Previous File Tab',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-next-file',
    actionId: 'editor-next-file',
    keys: 'alt+arrowright',
    description: 'Next File Tab',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-close-file',
    actionId: 'editor-close-file',
    keys: 'control+w',
    description: 'Close File Tab',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-switch-file',
    actionId: 'editor-switch-file',
    keys: 'control+tab',
    description: 'Switch File Tab',
    category: 'Editor',
    context: 'editor',
  },
  {
    id: 'editor-fullscreen',
    actionId: 'editor-fullscreen',
    keys: 'f11',
    description: 'Toggle Fullscreen Editor',
    category: 'Editor',
    context: 'editor',
  },

  // Dependency Graph Shortcuts (Graph Context)
  {
    id: 'graph-zoom-in',
    actionId: 'graph-zoom-in',
    keys: '+',
    description: 'Zoom In Graph',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-zoom-out',
    actionId: 'graph-zoom-out',
    keys: '-',
    description: 'Zoom Out Graph',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-reset-zoom',
    actionId: 'graph-reset-zoom',
    keys: '0',
    description: 'Reset Zoom',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-fit',
    actionId: 'graph-fit',
    keys: 'f',
    description: 'Fit Graph on Screen',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-center-node',
    actionId: 'graph-center-node',
    keys: 'c',
    description: 'Center Selected Node',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-focus-search',
    actionId: 'graph-focus-search',
    keys: 's',
    description: 'Focus Search Box',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-nav-up',
    actionId: 'graph-nav-up',
    keys: 'arrowup',
    description: 'Navigate Nodes Up',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-nav-down',
    actionId: 'graph-nav-down',
    keys: 'arrowdown',
    description: 'Navigate Nodes Down',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-nav-left',
    actionId: 'graph-nav-left',
    keys: 'arrowleft',
    description: 'Navigate Nodes Left',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-nav-right',
    actionId: 'graph-nav-right',
    keys: 'arrowright',
    description: 'Navigate Nodes Right',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-open-node',
    actionId: 'graph-open-node',
    keys: 'enter',
    description: 'Open Node Details',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-highlight-dependencies',
    actionId: 'graph-highlight-dependencies',
    keys: 'space',
    description: 'Highlight Dependencies',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-hide-node',
    actionId: 'graph-hide-node',
    keys: 'delete',
    description: 'Hide Selected Node',
    category: 'Dependency Graph',
    context: 'graph',
  },
  {
    id: 'graph-clear-selection',
    actionId: 'graph-clear-selection',
    keys: 'escape',
    description: 'Clear Node Selection',
    category: 'Dependency Graph',
    context: 'graph',
  },

  // Job List Shortcuts (JobList Context)
  {
    id: 'joblist-prev',
    actionId: 'joblist-prev',
    keys: 'arrowup',
    description: 'Previous Job',
    category: 'Migration',
    context: 'joblist',
  },
  {
    id: 'joblist-next',
    actionId: 'joblist-next',
    keys: 'arrowdown',
    description: 'Next Job',
    category: 'Migration',
    context: 'joblist',
  },
  {
    id: 'joblist-open',
    actionId: 'joblist-open',
    keys: 'enter',
    description: 'Open Selected Job',
    category: 'Migration',
    context: 'joblist',
  },
  {
    id: 'joblist-download',
    actionId: 'joblist-download',
    keys: 'control+enter',
    description: 'Download Output ZIP',
    category: 'Migration',
    context: 'joblist',
  },
  {
    id: 'joblist-delete',
    actionId: 'joblist-delete',
    keys: 'delete',
    description: 'Remove Job from History',
    category: 'Migration',
    context: 'joblist',
  },
  {
    id: 'joblist-refresh',
    actionId: 'joblist-refresh',
    keys: 'f5',
    description: 'Refresh Jobs List',
    category: 'Migration',
    context: 'joblist',
  },

  // Dialog Shortcuts (Dialog Context)
  {
    id: 'dialog-close',
    actionId: 'dialog-close',
    keys: 'escape',
    description: 'Close Dialog',
    category: 'General',
    context: 'dialog',
  },
  {
    id: 'dialog-confirm',
    actionId: 'dialog-confirm',
    keys: 'enter',
    description: 'Confirm Action',
    category: 'General',
    context: 'dialog',
  },
  {
    id: 'dialog-primary',
    actionId: 'dialog-primary',
    keys: 'space',
    description: 'Trigger Primary Action',
    category: 'General',
    context: 'dialog',
  },
];
